# Generated by Django 4.2.3 on 2023-07-20 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_tagtype_tag_parents_alter_card_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 20, 17, 37, 22, 916673)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ImagePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.FloatField()),
                ('start_y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('scale', models.FloatField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.card')),
                ('tags', models.ManyToManyField(blank=True, to='Main.tag')),
            ],
        ),
    ]
