# Generated by Django 4.2.3 on 2023-07-22 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_card_created_at_imagepart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='parents',
        ),
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.tag'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagepart',
            name='scale',
            field=models.FloatField(default=1),
        ),
    ]
